name: meet_gdsc_appdev_task
description: A task app for DJSCE GDSC made by Meet Chavan
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  get: ^4.6.5
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans.ttf
  
 